### ISSUE TITLE
Suggestion: Text only notifications

### ISSUE THREAD

**Issue by batugn** [hacettepeoyt/hu-cafeteria-bot#3]
Having image based daily menus are great, though they will not be shown on most device notifications. If possible, there should be a text-only fork of the same bot, which can be useful for people like me, who doesn't really use Telegram frequently and/or just wants to get notified about the daily menu without checking any page, directly or indirectly.

**Comment by furkansimsekli** [comment]
I see your point. So, are you suggesting that we should create another Telegram channel for text only menus? Since the users don't directly interact with the bot, we may need to create another channel.

Before you ask, I should say this: I don't want people to interact with the bot because I want to keep it simple. In case of that, I need to use user database to notify them when the *time* comes.

**Comment by bthngn** [comment]
I suggest there should be a text only seperate channel. Having a user
preferences panel would be a hassle at this moment.

**Comment by furkansimsekli** [comment]
Good idea, I'll add this feature when I'm available. 
However, new contributors are welcome! It's relatively easy task to do, [fetch_data_fromXML](https://github.com/hacettepeoyt/hu-cafeteria-bot/blob/d2f5980edbe26f25f837d655af7896f77d88387b/src/scraper.py#L5) already returns a clean data. After that, all you're going to do is prepare a message for [Telegram Channel](https://t.me/hacettepeyemekhaneText).
